-- 1. Create the 'leads' table
CREATE TABLE leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  company TEXT,
  budget TEXT,
  message TEXT
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow anyone to insert (Anon access)
CREATE POLICY "Allow public insert to leads" 
ON leads 
FOR INSERT 
WITH CHECK (true);

-- 4. Create a policy to allow only authenticated users to view leads (Optional)
-- CREATE POLICY "Allow authenticated view only" 
-- ON leads 
-- FOR SELECT 
-- USING (auth.role() = 'authenticated');
